[package]
name = "verilated-module"
version = "0.0.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.2"
quote = "0.4.2"
syn = { version = "0.12.14", features = ["full"] }
