[package]
name = "verilated-module"
version = "0.0.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "0.5"
syn = { version = "0.13", features = ["full"] }
