[package]
name = "verilator"
version = "0.0.0"
authors = ["Dan Glastonbury <dan.glastonbury@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Automated generation of verilator test modules."

[dependencies]
cc = { version = "1.0", optional = true }
fnv = { version = "1.0", optional = true }
syntex_syntax = { version = "0.59.1", optional = true }

[features]
gen = ["cc"]
module = ["fnv", "syntex_syntax"]
default = ["gen"]